class Document {
  final int? id;
  final String title;
  final String category;
  final String ocrText;
  final String imagePath; // first scanned page, used as a thumbnail/preview
  final String pdfPath; // PDF generated by the scanner for the whole document
  final DateTime createdAt;

  Document({
    this.id,
    required this.title,
    required this.category,
    required this.ocrText,
    required this.imagePath,
    required this.pdfPath,
    required this.createdAt,
  });
}